### ISSUE TITLE
FastAsyncWorldEdit Not Working With Thermos

### ISSUE THREAD

**Issue by BungeeTheCookie** [boy0001/FastAsyncWorldedit#198]
Hello, when I add FAWE to Thermos, I cannot edit the world and plugin config files are not getting generated. This is a **confirmed** FAWE issue because if I remove the mod, it works just fine. In my mods folder I have worldedit-forge-6.1.2 and the latest version of FAWE. In my plugins folder I have worldedit-bukkit-6.1.4 and worldguard-6.1.2. If I remove FAWE and keep the other plugins / mods there, it works fine. I get this error when I run /stop

http://pastebin.com/FRDr4nVj 

@boy0001

**Comment by boy0001** [comment]
You need to use the forge version.

**Comment by BungeeTheCookie** [comment]
@boy0001 I was using the Forge version...

**Comment by BungeeTheCookie** [comment]
I forgot to mention I am using 1.7.10

**Comment by BungeeTheCookie** [comment]
@boy0001 Has this been fixed in the later commits?

**Comment by boy0001** [comment]
Forge version is stable, I haven't tested with worldedit bukkit also installed.

**Comment by BungeeTheCookie** [comment]
@boy0001 
Oh okay, I am using WorldEdit Forge and WorldEdit Bukkit in tandem (as some plugins require WorldEdit Bukkit)

**Comment by BungeeTheCookie** [comment]
@boy0001 
Any status on the issue? :P

**Comment by Fluxty** [comment]
I would also like this to work. AWE is giving us a headache.

**Comment by BungeeTheCookie** [comment]
@boy0001 
Have you looked into this? The issue still persists, and I would love to have it fixed.

**Comment by boy0001** [comment]
Latest version I have working on thermos for 1.7.10, try it out.

**Comment by BungeeTheCookie** [comment]
@boy0001 Awesome!

**Comment by BungeeTheCookie** [comment]
@boy0001 
The problem still persists. Have you tried with WorldEdit (Forge), WorldEdit (Bukkit), and WorldGuard (Bukkit) all installed?

**Comment by boy0001** [comment]
I didn't have WorldGuard installed, but I had both WorldEdits and FAWE forge installed.

**Comment by BungeeTheCookie** [comment]
Which versions were you using? The error occurs when you run /stop and when players are online. Also having this installed prevents mcMMO from loading properly, those are just 2 effects.

**Comment by boy0001** [comment]
Still an issue?

**Comment by Noire86** [comment]
FAWE is not working with MCMMO. Its actual on 10.03.2018. Using latest FAWE 1.7.10 forge, WE 6.1.1, WE 6.7.3.1-bukkit.

MCMMO fails with this error on startup: [13:38:10] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.02-SNAPSHOT-b31
[13:38:10] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[13:38:10] [Server thread/INFO]: [mcMMO] Please do not replace the mcMMO jar while the server is running.
[13:38:10] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.02-SNAPSHOT-b31
[13:38:11] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.02-SNAPSHOT-b31 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.gmail.nossr50.datatypes.skills.SkillType
	at com.gmail.nossr50.config.AdvancedConfig.getMaxChance(AdvancedConfig.java:693) ~[?:?]
	at com.gmail.nossr50.config.AdvancedConfig.validateKeys(AdvancedConfig.java:48) ~[?:?]
	at com.gmail.nossr50.config.ConfigLoader.validate(ConfigLoader.java:62) ~[?:?]
	at com.gmail.nossr50.config.AdvancedConfig.<init>(AdvancedConfig.java:22) ~[?:?]
	at com.gmail.nossr50.config.AdvancedConfig.getInstance(AdvancedConfig.java:27) ~[?:?]
	at com.gmail.nossr50.skills.alchemy.Alchemy.<clinit>(Alchemy.java:51) ~[?:?]
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:215) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:318) ~[JavaPlugin.class:1.7.10-1614.58]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:392) [JavaPluginLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:429) [SimplePluginManager.class:1.7.10-1614.58]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:205) [mcMMO.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) [JavaPlugin.class:1.7.10-1614.58]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.58]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:463) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:374) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by evernife** [comment]
any progress ?

**Comment by evernife** [comment]
**FastAsyncWorldEdit-forge1710-18.10.05-f3fdef6-1218-21.5.5.jar** is working well with:

worldedit-forge-mc1.7.10-6.1.1-dist.jar
worldedit-bukkit-6.1.7-SNAPSHOT-dist.jar
worldguard-6.1.jar

**Comment by ResqDiver1317** [comment]
Evernife, Where did you download the 6.1.7 snapshot for bukkit at? I have FastAsyncWorldEdit-forge1710-18.10.25-626169a-1227-21.5.14 and WE Forge 6.1.1, but the latest WE Bukkit I can find is 6.1 and when I start my server, I get ZERO worldedit functions and my log talks about the version mismatch between the 2 world edit versions
