### ISSUE TITLE
error 1.13.1

### ISSUE THREAD

**Issue by Mathieu57** [boy0001/FastAsyncWorldedit#1237]
Does not work on spigot 1.13.1

[13:12:01] [Server thread/INFO]: MathieuAR_ALT issued server command: //expand vert
[13:12:04] [Server thread/INFO]: MathieuAR_ALT issued server command: //copy
[13:12:04] [Craft Scheduler Thread - 17/ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.NBTTagByte.asByte()B
	at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:414) ~[FastAsyncWorldEdit-bukkit-18.12.24-4198932-2085.jar:?]
	at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:410) ~[FastAsyncWorldEdit-bukkit-18.12.24-4198932-2085.jar:?]
	at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.getEntity(Spigot_v1_13_R2.java:317) ~[FastAsyncWorldEdit-bukkit-18.12.24-4198932-2085.jar:?]
	at com.sk89q.worldedit.bukkit.BukkitEntity.getState(BukkitEntity.java:84) ~[FastAsyncWorldEdit-bukkit-18.12.24-4198932-2085.jar:?]
	at com.sk89q.worldedit.function.operation.ForwardExtentCopy.lambda$resume$2(ForwardExtentCopy.java:355) ~[FastAsyncWorldEdit-bukkit-18.12.24-4198932-2085.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_191]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_191]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_191]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_191]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_191]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_191]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_191]
	at com.sk89q.worldedit.function.operation.ForwardExtentCopy.resume(ForwardExtentCopy.java:357) ~[FastAsyncWorldEdit-bukkit-18.12.24-4198932-2085.jar:?]
	at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:68) ~[FastAsyncWorldEdit-bukkit-18.12.24-4198932-2085.jar:?]
	at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:55) ~[FastAsyncWorldEdit-bukkit-18.12.24-4198932-2085.jar:?]
	at com.sk89q.worldedit.command.ClipboardCommands.lambda$copy$0(ClipboardCommands.java:180) ~[FastAsyncWorldEdit-bukkit-18.12.24-4198932-2085.jar:?]
	at com.boydti.fawe.object.FawePlayer.checkConfirmationRegion(FawePlayer.java:237) ~[FastAsyncWorldEdit-bukkit-18.12.24-4198932-2085.jar:?]
	at com.sk89q.worldedit.command.ClipboardCommands.copy(ClipboardCommands.java:162) ~[FastAsyncWorldEdit-bukkit-18.12.24-4198932-2085.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:265) ~[FastAsyncWorldEdit-bukkit-18.12.24-4198932-2085.jar:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[FastAsyncWorldEdit-bukkit-18.12.24-4198932-2085.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$2.get(CommandManager.java:414) ~[FastAsyncWorldEdit-bukkit-18.12.24-4198932-2085.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:437) ~[FastAsyncWorldEdit-bukkit-18.12.24-4198932-2085.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:418) ~[FastAsyncWorldEdit-bukkit-18.12.24-4198932-2085.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$3$1.run(CommandManager.java:536) ~[FastAsyncWorldEdit-bukkit-18.12.24-4198932-2085.jar:?]
	at com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:328) ~[FastAsyncWorldEdit-bukkit-18.12.24-4198932-2085.jar:?]
	at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) [FastAsyncWorldEdit-bukkit-18.12.24-4198932-2085.jar:?]
	at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) [FastAsyncWorldEdit-bukkit-18.12.24-4198932-2085.jar:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) [server.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-f6a273b-a639ae4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
